package dev.falkow.blanco.layout.display.theme

// val colorThemeMap = mapOf<ColorThemes, Pair<ColorScheme, ColorScheme>>(
//     ColorThemes.BLUE to getAppColorTheme(colorSetBlue),
//     ColorThemes.GREEN to getAppColorTheme(colorSetGreen),
//     ColorThemes.INDIGO to getAppColorTheme(colorSetIndigo),
//     ColorThemes.SAND to getAppColorTheme(colorSetSand),
//     ColorThemes.TEAL to getAppColorTheme(colorSetTeal),
// )
//
// private fun getAppColorTheme(appColorSet: AppColorSet): Pair<ColorScheme, ColorScheme> =
//     Pair(
//         lightColorScheme(
//             primary = appColorSet.md_theme_light_primary,
//             onPrimary = appColorSet.md_theme_light_onPrimary,
//             primaryContainer = appColorSet.md_theme_light_primaryContainer,
//             onPrimaryContainer = appColorSet.md_theme_light_onPrimaryContainer,
//             secondary = appColorSet.md_theme_light_secondary,
//             onSecondary = appColorSet.md_theme_light_onSecondary,
//             secondaryContainer = appColorSet.md_theme_light_secondaryContainer,
//             onSecondaryContainer = appColorSet.md_theme_light_onSecondaryContainer,
//             tertiary = appColorSet.md_theme_light_tertiary,
//             onTertiary = appColorSet.md_theme_light_onTertiary,
//             tertiaryContainer = appColorSet.md_theme_light_tertiaryContainer,
//             onTertiaryContainer = appColorSet.md_theme_light_onTertiaryContainer,
//             error = appColorSet.md_theme_light_error,
//             errorContainer = appColorSet.md_theme_light_errorContainer,
//             onError = appColorSet.md_theme_light_onError,
//             onErrorContainer = appColorSet.md_theme_light_onErrorContainer,
//             background = appColorSet.md_theme_light_background,
//             onBackground = appColorSet.md_theme_light_onBackground,
//             surface = appColorSet.md_theme_light_surface,
//             onSurface = appColorSet.md_theme_light_onSurface,
//             surfaceVariant = appColorSet.md_theme_light_surfaceVariant,
//             onSurfaceVariant = appColorSet.md_theme_light_onSurfaceVariant,
//             outline = appColorSet.md_theme_light_outline,
//             inverseOnSurface = appColorSet.md_theme_light_inverseOnSurface,
//             inverseSurface = appColorSet.md_theme_light_inverseSurface,
//             inversePrimary = appColorSet.md_theme_light_inversePrimary,
//             surfaceTint = appColorSet.md_theme_light_surfaceTint,
//         ),
//         darkColorScheme(
//             primary = appColorSet.md_theme_dark_primary,
//             onPrimary = appColorSet.md_theme_dark_onPrimary,
//             primaryContainer = appColorSet.md_theme_dark_primaryContainer,
//             onPrimaryContainer = appColorSet.md_theme_dark_onPrimaryContainer,
//             secondary = appColorSet.md_theme_dark_secondary,
//             onSecondary = appColorSet.md_theme_dark_onSecondary,
//             secondaryContainer = appColorSet.md_theme_dark_secondaryContainer,
//             onSecondaryContainer = appColorSet.md_theme_dark_onSecondaryContainer,
//             tertiary = appColorSet.md_theme_dark_tertiary,
//             onTertiary = appColorSet.md_theme_dark_onTertiary,
//             tertiaryContainer = appColorSet.md_theme_dark_tertiaryContainer,
//             onTertiaryContainer = appColorSet.md_theme_dark_onTertiaryContainer,
//             error = appColorSet.md_theme_dark_error,
//             errorContainer = appColorSet.md_theme_dark_errorContainer,
//             onError = appColorSet.md_theme_dark_onError,
//             onErrorContainer = appColorSet.md_theme_dark_onErrorContainer,
//             background = appColorSet.md_theme_dark_background,
//             onBackground = appColorSet.md_theme_dark_onBackground,
//             surface = appColorSet.md_theme_dark_surface,
//             onSurface = appColorSet.md_theme_dark_onSurface,
//             surfaceVariant = appColorSet.md_theme_dark_surfaceVariant,
//             onSurfaceVariant = appColorSet.md_theme_dark_onSurfaceVariant,
//             outline = appColorSet.md_theme_dark_outline,
//             inverseOnSurface = appColorSet.md_theme_dark_inverseOnSurface,
//             inverseSurface = appColorSet.md_theme_dark_inverseSurface,
//             inversePrimary = appColorSet.md_theme_dark_inversePrimary,
//             surfaceTint = appColorSet.md_theme_dark_surfaceTint,
//         )
//     )