package dev.falkow.blanco.layout.display.theme

import androidx.compose.ui.graphics.Color

val colorSetSand = AppColorSet(

    seed = Color(0xFFF2E0BD),

    md_theme_light_primary = Color(0xFF775A00),
    md_theme_light_onPrimary = Color(0xFFFFFFFF),
    md_theme_light_primaryContainer = Color(0xFFFFDF98),
    md_theme_light_onPrimaryContainer = Color(0xFF251A00),
    md_theme_light_secondary = Color(0xFF6A5D3F),
    md_theme_light_onSecondary = Color(0xFFFFFFFF),
    md_theme_light_secondaryContainer = Color(0xFFF4E0BB),
    md_theme_light_onSecondaryContainer = Color(0xFF241A04),
    md_theme_light_tertiary = Color(0xFF496548),
    md_theme_light_onTertiary = Color(0xFFFFFFFF),
    md_theme_light_tertiaryContainer = Color(0xFFCAEBC6),
    md_theme_light_onTertiaryContainer = Color(0xFF06210A),
    md_theme_light_error = Color(0xFFBA1A1A),
    md_theme_light_errorContainer = Color(0xFFFFDAD6),
    md_theme_light_onError = Color(0xFFFFFFFF),
    md_theme_light_onErrorContainer = Color(0xFF410002),
    md_theme_light_background = Color(0xFFFFFBFF),
    md_theme_light_onBackground = Color(0xFF1E1B16),
    md_theme_light_surface = Color(0xFFFFFBFF),
    md_theme_light_onSurface = Color(0xFF1E1B16),
    md_theme_light_surfaceVariant = Color(0xFFECE1CF),
    md_theme_light_onSurfaceVariant = Color(0xFF4D4639),
    md_theme_light_outline = Color(0xFF7E7667),
    md_theme_light_inverseOnSurface = Color(0xFFF7F0E7),
    md_theme_light_inverseSurface = Color(0xFF33302A),
    md_theme_light_inversePrimary = Color(0xFFEFC048),
    md_theme_light_shadow = Color(0xFF000000),
    md_theme_light_surfaceTint = Color(0xFF775A00),
    md_theme_light_outlineVariant = Color(0xFFD0C5B4),
    md_theme_light_scrim = Color(0xFF000000),

    md_theme_dark_primary = Color(0xFFEFC048),
    md_theme_dark_onPrimary = Color(0xFF3E2E00),
    md_theme_dark_primaryContainer = Color(0xFF5A4300),
    md_theme_dark_onPrimaryContainer = Color(0xFFFFDF98),
    md_theme_dark_secondary = Color(0xFFD7C5A0),
    md_theme_dark_onSecondary = Color(0xFF3A2F15),
    md_theme_dark_secondaryContainer = Color(0xFF52452A),
    md_theme_dark_onSecondaryContainer = Color(0xFFF4E0BB),
    md_theme_dark_tertiary = Color(0xFFAFCFAB),
    md_theme_dark_onTertiary = Color(0xFF1B361D),
    md_theme_dark_tertiaryContainer = Color(0xFF324D32),
    md_theme_dark_onTertiaryContainer = Color(0xFFCAEBC6),
    md_theme_dark_error = Color(0xFFFFB4AB),
    md_theme_dark_errorContainer = Color(0xFF93000A),
    md_theme_dark_onError = Color(0xFF690005),
    md_theme_dark_onErrorContainer = Color(0xFFFFDAD6),
    md_theme_dark_background = Color(0xFF1E1B16),
    md_theme_dark_onBackground = Color(0xFFE9E1D9),
    md_theme_dark_surface = Color(0xFF1E1B16),
    md_theme_dark_onSurface = Color(0xFFE9E1D9),
    md_theme_dark_surfaceVariant = Color(0xFF4D4639),
    md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4),
    md_theme_dark_outline = Color(0xFF999080),
    md_theme_dark_inverseOnSurface = Color(0xFF1E1B16),
    md_theme_dark_inverseSurface = Color(0xFFE9E1D9),
    md_theme_dark_inversePrimary = Color(0xFF775A00),
    md_theme_dark_shadow = Color(0xFF000000),
    md_theme_dark_surfaceTint = Color(0xFFEFC048),
    md_theme_dark_outlineVariant = Color(0xFF4D4639),
    md_theme_dark_scrim = Color(0xFF000000),
)