package dev.falkow.blanco.layout.display.theme

import androidx.compose.ui.graphics.Color

val colorSetIndigo = AppColorSet(

    seed = Color(0xFF6750A4),

    md_theme_light_primary = Color(0xFF6750A4),
    md_theme_light_onPrimary = Color(0xFFFFFFFF),
    md_theme_light_primaryContainer = Color(0xFFEADDFF),
    md_theme_light_onPrimaryContainer = Color(0xFF21005D),
    md_theme_light_secondary = Color(0xFF625B71),
    md_theme_light_onSecondary = Color(0xFFFFFFFF),
    md_theme_light_secondaryContainer = Color(0xFFE8DEF8),
    md_theme_light_onSecondaryContainer = Color(0xFF1D192B),
    md_theme_light_tertiary = Color(0xFF7D5260),
    md_theme_light_onTertiary = Color(0xFFFFFFFF),
    md_theme_light_tertiaryContainer = Color(0xFFFFD8E4),
    md_theme_light_onTertiaryContainer = Color(0xFF31111D),
    md_theme_light_error = Color(0xFFB3261E),
    md_theme_light_onError = Color(0xFFFFFFFF),
    md_theme_light_errorContainer = Color(0xFFF9DEDC),
    md_theme_light_onErrorContainer = Color(0xFF410E0B),
    md_theme_light_outline = Color(0xFF79747E),
    md_theme_light_background = Color(0xFFFFFBFE),
    md_theme_light_onBackground = Color(0xFF1C1B1F),
    md_theme_light_surface = Color(0xFFFFFBFE),
    md_theme_light_onSurface = Color(0xFF1C1B1F),
    md_theme_light_surfaceVariant = Color(0xFFE7E0EC),
    md_theme_light_onSurfaceVariant = Color(0xFF49454F),
    md_theme_light_inverseSurface = Color(0xFF313033),
    md_theme_light_inverseOnSurface = Color(0xFFF4EFF4),
    md_theme_light_inversePrimary = Color(0xFFD0BCFF),
    md_theme_light_shadow = Color(0xFF000000),
    md_theme_light_surfaceTint = Color(0xFF6750A4),
    md_theme_light_outlineVariant = Color(0xFFCAC4D0),
    md_theme_light_scrim = Color(0xFF000000),

    md_theme_dark_primary = Color(0xFFD0BCFF),
    md_theme_dark_onPrimary = Color(0xFF381E72),
    md_theme_dark_primaryContainer = Color(0xFF4F378B),
    md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF),
    md_theme_dark_secondary = Color(0xFFCCC2DC),
    md_theme_dark_onSecondary = Color(0xFF332D41),
    md_theme_dark_secondaryContainer = Color(0xFF4A4458),
    md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8),
    md_theme_dark_tertiary = Color(0xFFEFB8C8),
    md_theme_dark_onTertiary = Color(0xFF492532),
    md_theme_dark_tertiaryContainer = Color(0xFF633B48),
    md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4),
    md_theme_dark_error = Color(0xFFF2B8B5),
    md_theme_dark_onError = Color(0xFF601410),
    md_theme_dark_errorContainer = Color(0xFF8C1D18),
    md_theme_dark_onErrorContainer = Color(0xFFF9DEDC),
    md_theme_dark_outline = Color(0xFF938F99),
    md_theme_dark_background = Color(0xFF1C1B1F),
    md_theme_dark_onBackground = Color(0xFFE6E1E5),
    md_theme_dark_surface = Color(0xFF1C1B1F),
    md_theme_dark_onSurface = Color(0xFFE6E1E5),
    md_theme_dark_surfaceVariant = Color(0xFF49454F),
    md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0),
    md_theme_dark_inverseSurface = Color(0xFFE6E1E5),
    md_theme_dark_inverseOnSurface = Color(0xFF313033),
    md_theme_dark_inversePrimary = Color(0xFF6750A4),
    md_theme_dark_shadow = Color(0xFF000000),
    md_theme_dark_surfaceTint = Color(0xFFD0BCFF),
    md_theme_dark_outlineVariant = Color(0xFF49454F),
    md_theme_dark_scrim = Color(0xFF000000),
)