package dev.falkow.blanco.layout.display.theme

import androidx.compose.ui.graphics.Color

val colorSetBlue = AppColorSet(

    seed = Color(0xFF516EA8),

    md_theme_light_primary = Color(0xFF315DA8),
    md_theme_light_onPrimary = Color(0xFFFFFFFF),
    md_theme_light_primaryContainer = Color(0xFFD8E2FF),
    md_theme_light_onPrimaryContainer = Color(0xFF001A41),
    md_theme_light_secondary = Color(0xFF575E71),
    md_theme_light_onSecondary = Color(0xFFFFFFFF),
    md_theme_light_secondaryContainer = Color(0xFFDBE2F9),
    md_theme_light_onSecondaryContainer = Color(0xFF141B2C),
    md_theme_light_tertiary = Color(0xFF715573),
    md_theme_light_onTertiary = Color(0xFFFFFFFF),
    md_theme_light_tertiaryContainer = Color(0xFFFBD7FC),
    md_theme_light_onTertiaryContainer = Color(0xFF29132D),
    md_theme_light_error = Color(0xFFBA1A1A),
    md_theme_light_errorContainer = Color(0xFFFFDAD6),
    md_theme_light_onError = Color(0xFFFFFFFF),
    md_theme_light_onErrorContainer = Color(0xFF410002),
    md_theme_light_background = Color(0xFFFEFBFF),
    md_theme_light_onBackground = Color(0xFF1B1B1F),
    md_theme_light_surface = Color(0xFFFEFBFF),
    md_theme_light_onSurface = Color(0xFF1B1B1F),
    md_theme_light_surfaceVariant = Color(0xFFE1E2EC),
    md_theme_light_onSurfaceVariant = Color(0xFF44474F),
    md_theme_light_outline = Color(0xFF75777F),
    md_theme_light_inverseOnSurface = Color(0xFFF2F0F4),
    md_theme_light_inverseSurface = Color(0xFF303033),
    md_theme_light_inversePrimary = Color(0xFFADC6FF),
    md_theme_light_shadow = Color(0xFF000000),
    md_theme_light_surfaceTint = Color(0xFF315DA8),
    md_theme_light_outlineVariant = Color(0xFFC4C6D0),
    md_theme_light_scrim = Color(0xFF000000),

    md_theme_dark_primary = Color(0xFFADC6FF),
    md_theme_dark_onPrimary = Color(0xFF002E69),
    md_theme_dark_primaryContainer = Color(0xFF10448F),
    md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF),
    md_theme_dark_secondary = Color(0xFFBFC6DC),
    md_theme_dark_onSecondary = Color(0xFF293041),
    md_theme_dark_secondaryContainer = Color(0xFF3F4759),
    md_theme_dark_onSecondaryContainer = Color(0xFFDBE2F9),
    md_theme_dark_tertiary = Color(0xFFDEBCDF),
    md_theme_dark_onTertiary = Color(0xFF402843),
    md_theme_dark_tertiaryContainer = Color(0xFF583E5B),
    md_theme_dark_onTertiaryContainer = Color(0xFFFBD7FC),
    md_theme_dark_error = Color(0xFFFFB4AB),
    md_theme_dark_errorContainer = Color(0xFF93000A),
    md_theme_dark_onError = Color(0xFF690005),
    md_theme_dark_onErrorContainer = Color(0xFFFFDAD6),
    md_theme_dark_background = Color(0xFF1B1B1F),
    md_theme_dark_onBackground = Color(0xFFE3E2E6),
    md_theme_dark_surface = Color(0xFF1B1B1F),
    md_theme_dark_onSurface = Color(0xFFE3E2E6),
    md_theme_dark_surfaceVariant = Color(0xFF44474F),
    md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0),
    md_theme_dark_outline = Color(0xFF8E9099),
    md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F),
    md_theme_dark_inverseSurface = Color(0xFFE3E2E6),
    md_theme_dark_inversePrimary = Color(0xFF315DA8),
    md_theme_dark_shadow = Color(0xFF000000),
    md_theme_dark_surfaceTint = Color(0xFFADC6FF),
    md_theme_dark_outlineVariant = Color(0xFF44474F),
    md_theme_dark_scrim = Color(0xFF000000),
)