package dev.falkow.blanco.layout.display.theme

import androidx.compose.ui.graphics.Color

val colorSetGreen = AppColorSet(

    seed = Color(0xFF6C9C5A),

    md_theme_light_primary = Color(0xFF336B23),
    md_theme_light_onPrimary = Color(0xFFFFFFFF),
    md_theme_light_primaryContainer = Color(0xFFB4F39B),
    md_theme_light_onPrimaryContainer = Color(0xFF032100),
    md_theme_light_secondary = Color(0xFF54624D),
    md_theme_light_onSecondary = Color(0xFFFFFFFF),
    md_theme_light_secondaryContainer = Color(0xFFD8E7CC),
    md_theme_light_onSecondaryContainer = Color(0xFF121F0E),
    md_theme_light_tertiary = Color(0xFF386668),
    md_theme_light_onTertiary = Color(0xFFFFFFFF),
    md_theme_light_tertiaryContainer = Color(0xFFBCEBED),
    md_theme_light_onTertiaryContainer = Color(0xFF002021),
    md_theme_light_error = Color(0xFFBA1A1A),
    md_theme_light_errorContainer = Color(0xFFFFDAD6),
    md_theme_light_onError = Color(0xFFFFFFFF),
    md_theme_light_onErrorContainer = Color(0xFF410002),
    md_theme_light_background = Color(0xFFFDFDF6),
    md_theme_light_onBackground = Color(0xFF1A1C18),
    md_theme_light_surface = Color(0xFFFDFDF6),
    md_theme_light_onSurface = Color(0xFF1A1C18),
    md_theme_light_surfaceVariant = Color(0xFFDFE4D7),
    md_theme_light_onSurfaceVariant = Color(0xFF43483F),
    md_theme_light_outline = Color(0xFF73796E),
    md_theme_light_inverseOnSurface = Color(0xFFF1F1EA),
    md_theme_light_inverseSurface = Color(0xFF2F312D),
    md_theme_light_inversePrimary = Color(0xFF99D781),
    md_theme_light_shadow = Color(0xFF000000),
    md_theme_light_surfaceTint = Color(0xFF336B23),
    md_theme_light_outlineVariant = Color(0xFFC3C8BC),
    md_theme_light_scrim = Color(0xFF000000),

    md_theme_dark_primary = Color(0xFF99D781),
    md_theme_dark_onPrimary = Color(0xFF083900),
    md_theme_dark_primaryContainer = Color(0xFF1A520B),
    md_theme_dark_onPrimaryContainer = Color(0xFFB4F39B),
    md_theme_dark_secondary = Color(0xFFBCCBB1),
    md_theme_dark_onSecondary = Color(0xFF273421),
    md_theme_dark_secondaryContainer = Color(0xFF3D4B36),
    md_theme_dark_onSecondaryContainer = Color(0xFFD8E7CC),
    md_theme_dark_tertiary = Color(0xFFA0CFD1),
    md_theme_dark_onTertiary = Color(0xFF003739),
    md_theme_dark_tertiaryContainer = Color(0xFF1E4E50),
    md_theme_dark_onTertiaryContainer = Color(0xFFBCEBED),
    md_theme_dark_error = Color(0xFFFFB4AB),
    md_theme_dark_errorContainer = Color(0xFF93000A),
    md_theme_dark_onError = Color(0xFF690005),
    md_theme_dark_onErrorContainer = Color(0xFFFFDAD6),
    md_theme_dark_background = Color(0xFF1A1C18),
    md_theme_dark_onBackground = Color(0xFFE3E3DC),
    md_theme_dark_surface = Color(0xFF1A1C18),
    md_theme_dark_onSurface = Color(0xFFE3E3DC),
    md_theme_dark_surfaceVariant = Color(0xFF43483F),
    md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC),
    md_theme_dark_outline = Color(0xFF8D9387),
    md_theme_dark_inverseOnSurface = Color(0xFF1A1C18),
    md_theme_dark_inverseSurface = Color(0xFFE3E3DC),
    md_theme_dark_inversePrimary = Color(0xFF336B23),
    md_theme_dark_shadow = Color(0xFF000000),
    md_theme_dark_surfaceTint = Color(0xFF99D781),
    md_theme_dark_outlineVariant = Color(0xFF43483F),
    md_theme_dark_scrim = Color(0xFF000000),
)